import Head from "next/head";
import Contacts from "../src/shared/screens/Contacts";

export default function Contatos() {
  return (
    <>
      <Head>
        <title>Martin Comercial</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Contacts />
    </>
  );
}
