import Head from "next/head";
import Home from "../src/shared/screens/Home";

export default function Index() {
  return (
    <>
      <Head>
        <title>Martin Comercial</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Home />
    </>
  );
}
