import Head from "next/head";
import Services from "../src/shared/screens/Services";

export default function Servicos() {
  return (
    <>
      <Head>
        <title>Martin Comercial</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Services />
    </>
  );
}
